name: Build IW7-Mod

on:
  push:
    branches:
      - main
    tags:
      - '*'  # This will trigger the workflow when any tag is pushed
  schedule:
    # - cron: "0 0 * * 0"  # Runs weekly on Sunday at midnight UTC
    # - cron: "*/1 * * * *"  # Runs every 1 minute
    - cron: "0 0 0 0 0"
jobs:
  build:
    name: Build binaries
    runs-on: windows-2022
    strategy:
      matrix:
        configuration:
          - Release
          - Debug
    steps:
      - name: Check out files
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          # NOTE - If LFS ever starts getting used during builds, switch this to true!
          lfs: false

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3

      - name: Generate project files
        run: tools/premake5 vs2022

      - name: Set up problem matching
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Build ${{matrix.configuration}} binaries
        run: msbuild /m /v:minimal /p:Configuration=${{matrix.configuration}} /p:Platform=x64 build/iw7-mod.sln

      - name: Upload ${{matrix.configuration}} binaries
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.configuration}} binaries
          path: |
            build/bin/x64/${{matrix.configuration}}/iw7-mod.exe
            build/bin/x64/${{matrix.configuration}}/iw7-mod.pdb
            
      - name: Upload ${{matrix.configuration}} data artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.configuration}} data artifacts
          path: |
            data/*