name: Build IW7-Mod

on:
  push:
    branches:
      - main
    tags:
      - '*'  # Trigger the workflow when any tag is pushed
  schedule:
    # - cron: "0 0 * * 0"  # Runs weekly on Sunday at midnight UTC
    # - cron: "*/1 * * * *"  # Runs every 1 minute
    - cron: "0 0 0 0 0"
jobs:
  build:
    name: Build binary
    runs-on: windows-latest
    strategy:
      matrix:
        configuration:
          - Release
    steps:
      - name: Check out files
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          # NOTE - If LFS ever starts getting used during builds, switch this to true!
          lfs: false

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3

      - name: Generate project files
        run: tools/premake5 vs2022

      - name: Set up problem matching
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Build ${{matrix.configuration}} binaries
        run: msbuild /m /v:minimal /p:Configuration=${{matrix.configuration}} /p:Platform=x64 build/iw7-mod.sln

      - name: Compile Installer
        run: |
          ./installer/compile.bat

      - name: Stage Release
        run: |
          mkdir release
          mv data release/iw7-mod
          mv build/bin/x64/${{matrix.configuration}}/iw7-mod.exe release/.
          mv build/bin/x64/${{matrix.configuration}}/tlsdll.dll release/.
          powershell -Command 'Compress-Archive -CompressionLevel Optimal -Force -Path release -DestinationPath iw7-mod.zip -Confirm:$false'
          powershell -Command 'Compress-Archive -CompressionLevel Optimal -Force -Path cfg/* -DestinationPath IW7DedicatedConfigs.zip -Confirm:$false'

      - name: Upload ${{matrix.configuration}} Installer
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.configuration}} binaries
          path: |
            installer/build/iw7-installer.exe

      - name: Upload ${{matrix.configuration}} ZIP
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.configuration}} binaries
          path: |
            iw7-mod.zip

      - name: Upload ${{matrix.configuration}} Server Configuration Files
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.configuration}} binaries
          path: |
            IW7DedicatedConfigs.zip

      - name: Upload ${{matrix.configuration}} binaries
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.configuration}} binaries
          path: |
            build/bin/x64/${{matrix.configuration}}/iw7-mod.exe

      - name: Upload ${{matrix.configuration}} debug info
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.configuration}} binaries
          path: |
            build/bin/x64/${{matrix.configuration}}/iw7-mod.pdb
            
      - name: Upload ${{matrix.configuration}} data artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.configuration}} data artifacts
          path: |
            data/*